### ISSUE TITLE
extract auth token from code

### ISSUE THREAD

**Issue by HenrikWolf** [HenrikWolf/MagicTools#1]
add properties file for authentication token
add properties file to .gitignore

**Comment by Rolfus187** [comment]
going to instead use input form for auth tokens

**Comment by HenrikWolf** [comment]
Stand jetzt:
Die Login-Tokens von Fendor stehen in den Properties und werden per JQuery als Default in die Inputfelder gesetzt.
Bei Klick auf den (noch falschen) Button werden die Werte der Inputs ausgelesen und für die Anmeldung als Objekt weitergegeben.
