### ISSUE TITLE
bug: page not loading using microsoft edge

### ISSUE THREAD

**Issue by Rolfus187** [HenrikWolf/MagicTools#12]
Message: Beim Laden dieser Seite ist ein Problem aufgetreten.
Wir haben ein paar Mal versucht, diese Seite zu laden, aber es gibt immer noch ein Problem mit der Website. Da Sie sicher wichtigere Dinge zu tun haben, als das Laden dieser Seite zu beobachten, empfehlen wir Ihnen, etwas später zu dieser Seite zurückzukehren.

Error is gone when removing the line: <.script type="module" src="javascript.js"><./script>
Error ist also present for version without the last commit (cf2a781) where I know it worked a few hours ago.

**Comment by Rolfus187** [comment]
The oldest working Version is 88fbda9, the one afterwards (getting the auth token from Input field) does not work.

**Comment by HenrikWolf** [comment]
solved for edge. But now there is an issue with firefox:
SyntaxError Missing { before class body

Maybe there is a problem with the default export in combination with other exports. To fix this, I'll add all properties for authentication to the default export class. Please test in edge.

**Comment by HenrikWolf** [comment]
still error in edge.

**Comment by HenrikWolf** [comment]
According to microsoft, edges newest version can deal with es6-modules...
I will test it.

**Comment by HenrikWolf** [comment]
Ich habe unser Tool ausgiebig mit einer aktuellen Version von Edge (Microsoft Edge 42.17134.1.0) getestet und es funktioniert nun einwandfrei!<br><br>

Der hauseigene Android-Browser soll in neuen Versionen (z.B. vorinstalliert ab Android Oreo?) ebenfalls es6-module unterstützen. Kannst du das mit deinem J3 einmal testen?<br><br>

Es klingt doch gut, dass da Bewegung in der Sache ist und es6-module offenbar keine Totgeburt sind ;-)<br><br>

Ticket kann damit geschlossen werden.<br><br>

**Comment by Rolfus187** [comment]
Bis jetzt nix unter Android auf dem eigenen Browser mit neuestem Update. Liegt aber ja nicht am Tool, also mal sehen ob es irgendwann geht :D
