### ISSUE TITLE
change output format of wants

### ISSUE THREAD

**Issue by Rolfus187** [HenrikWolf/MagicTools#15]
the format for outputted wants has to he decided.
I think the following Information should be outputted:

- Cardname
- Count
- Set (if specified)

and maybe:
- foil yes/no
- maybe other like language, grading...

 I propose something like:
COUNTx CARDNAME (SET, FOIL, OTHER...)

**Comment by Rolfus187** [comment]
Currently Count and Cardname are always displayed.
Displayed if specified are: Set and Foil.

Also, easy method of adding other additional information if needed was implemented, just push any additional information to the "additionalInfo" array.

**Comment by HenrikWolf** [comment]
It looks great for the moment.
For further improvement or new features we should create specific issues.
