### ISSUE TITLE
bug: tab "add account" not setting deactive on other tabs

### ISSUE THREAD

**Issue by Rolfus187** [HenrikWolf/MagicTools#21]
Wenn man "neuen Account" auswählt und anschließen zurück auf den gleich Tab wie vorher möchte (etwa Export) macht ein klick auf den Menüpunkt nichts. Ein anderer funktioniert problemlos. Der tab bleibt active auch wenn weg gewechselt wird. Das gleiche gilt für die Account-Verwaltung tabs: wenn man einen (z.B neuer benutzer) wählt, dann auf z.B. export wechselt, kann man nicht zurück auf "neuen benutzer".

Das ganze sieht nach zwei separaten Menüleisten aus die aber das gleiche steuern, es aber zwei gleichzeitig "aktive" menüeinträge geben kann. Das sollte wohl vereinheitlicht werden.

**Comment by Rolfus187** [comment]
Ich hab momentan nicht so viel Zeit, wenn ich dazu komme schaue ich mir das aber mal an

**Comment by HenrikWolf** [comment]
Das Problem hat mich schon länger beschäftigt und sollte eigentlich auch (provisorisch) gelöst sein. Probiere mal den Cache zu leeren. Ansonsten kann es sein, dass der Work-Around-Code in der online-Version gerade auskommentiert ist...

Hintergrunde:
Genau, es sind zwei unabhängige Navs oben. Das liegt daran, dass ich es nicht hinbekommen habe, einen Teil linksbündig und einen anderen Teil rechtsbündig zu platzieren. Geht bestimmt irgendwie mit Margins und/oder Platzhalter-Divs, ist aber fummelig. Um mich damit nicht zu sehr aufzuhalten, habe ich per js-funktion das "active"-element aktualisieren lassen.

**Comment by Rolfus187** [comment]
Jo ich sehe dass das nur bei mir der Fall ist und nicht online, ist also gelöst! Sorry dann für das Aufmachen des issues.

**Comment by HenrikWolf** [comment]
Dafür sind Issues da!
Wir können es auch offen lassen, wenn wir eine schönere Lösung mit nur einer Navigation basteln wollen.

Allgemein kann es immer sein, dass sie online-version von der github-version abweicht. Die Github-Version sollte aber immer so gut es geht funktionstüchtig und bereits getestet sein.
