### ISSUE TITLE
remove Get Lists Button

### ISSUE THREAD

**Issue by HenrikWolf** [HenrikWolf/MagicTools#25]
Entferne Get List Button. 

Es gibt zwei Möglichkeiten die Liste automatisch zu laden:

**1. Sobald sich ein User angemeldet hat.**
**Vorteile:** Die Zeit wird sofort genutzt. Wenn der User den Export nutzen möchte, ist die Liste schon geladen oder fast geladen. Wenn ein User die Export-Seite mehrmals aufruft, wird nicht erneut geladen (Unnötige Anfragen)
**Nachteile:** Die Liste wird auch geladen, wenn der Export nicht aufgerufen wird (unnötige Anfragen). Wenn der User sofort auf den Export geht, könnte er sich wundern, dass noch keine Liste angezeigt wird.

**2. Sobald der User den Export besucht.**
Vor- und Nachteil entsprechend anders herum.

**Comment by Rolfus187** [comment]
Ich bin für Möglichkeit 1.
Das ganze hat noch einen Vorteil: Falls irgendein anderes Tool auch die bestehenden Wantlists braucht (was ich mir gut vorstellen kann) sind sie auch bereits geladen und müssen dann nur einmal geladen werden.

**Comment by HenrikWolf** [comment]
Ich habe das Ticket umgesetzt und dabei auch etwas Redundanz bei der Abfrage nach den User-Daten (Liste der Wantlists, Daten für editUser-Form) entfernt. 

Ein Problem, auf das ich gestoßen bin war, dass ich nicht einfach am Ende des Logins das Dropdown füllen kann, weil das neu-Laden der website parallel arbeitet und noch nicht abgeschlossen ist. Ich muss also darauf warten. Deshalb erfolgt das Füllen des Dropdowns (und des userEdit Formulars) nach dem Laden der Webseite. Das wiederum bedeutet, dass auch beim ersten Aufruf (wo noch kein User angemeldet ist) versucht wird, das Dropdown zu füllen.

Ein weiterer Punkt ist die Wechselwirkung mit editUser... Sobald die Daten akualisiert werden muss die Dropdown-Liste ebenfalls aktualisiert werden. Sollte aber auch passieren.

**Comment by HenrikWolf** [comment]
Wenn Dir noch etwas schlaues dazu einfällt, her damit. Ansonsten: Kann geschlossen werden.

**Comment by Rolfus187** [comment]
Klingt soweit doch gut, ich schließe mal.
