### ISSUE TITLE
create dev directory with testing space

### ISSUE THREAD

**Issue by Rolfus187** [HenrikWolf/MagicTools#27]
Wir wollte einen Ordner /dev/ haben in der wir jeweils testen können ohne uns in die Quere zu kommen und ohne den "Release" der von anderen dann genutzt werden kann zu beeinträchtigen.

Ich assigne dich mal dafür :D

**Comment by HenrikWolf** [comment]
Erledigt.

Es gibt folgende Verzeichnisse:
/MagicTools --> Release Version
/MagicTools/dev/henrik --> Henriks Test Version
/MagicTools/dev/Finn --> Finns Test Version

Dein Verzeichnis ist leer. Wenn du mit remote-sync arbeiten möchtest, musst du den Pfad ändern:
Rechtsklick auf dein Projektverzeichnis, Remote Sync, config...

Von meiner Seite aus closed.
