### ISSUE TITLE
add mouseover to nav-pills

### ISSUE THREAD

**Issue by HenrikWolf** [HenrikWolf/MagicTools#31]
color: darkgrey

**Comment by HenrikWolf** [comment]
Erledigt. Wenn du die Farbe okay findest, kann das Ticket geschlossen werden.

Btw: Das Farbschema ist garkein echtes grau, sondern hat einen leichten blau-touch. ;-) Die rgb Farben lassen sich aber schnell aus dem bootstrap.css herauslesen.

**Comment by Rolfus187** [comment]
Sieht gut aus!
