### ISSUE TITLE
bug: cross-origin-request blocked

### ISSUE THREAD

**Issue by HenrikWolf** [HenrikWolf/MagicTools#5]

**Comment by HenrikWolf** [comment]
"Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://api.cardmarket.com/ws/v2.0/output.json/account66. (Grund: CORS-Preflight-Kanal war nicht erfolgreich)."
This error occurs if the request url is incorrect.

**Comment by Rolfus187** [comment]
Had this error for every API acces i tried two days ago. Now everything is working fine. Maybe Server error on mkm side?

**Comment by HenrikWolf** [comment]
I still have the message if the mkm_url (properties) is wrong.

**Comment by HenrikWolf** [comment]
Anscheinend ist das eine übliche Fehlermeldung, wenn die URL ungültig (was auch immer ungültig ist... Z.b. nicht vorhanden) ist. Solange uns der Fehler nicht noch an anderer Stelle begegnet, sollte uns das jetzt egal sein. Hast du noch etwas herausgefunden?

Ich schlage deswegen vor, dieses Ticket zu schließen.
