### ISSUE TITLE
add loading Spinner

### ISSUE THREAD

**Issue by HenrikWolf** [HenrikWolf/MagicTools#8]
add a loading icon while waiting of Server responses

There is an Icon from fontawesome. There is a possibility to rotate the Icon.

**Comment by Rolfus187** [comment]
spinner is added but a bit off place, i cant get it to be where i want ist to be

**Comment by Rolfus187** [comment]
I worked something out, but the code is ugly (needing 4 css classes in total, 2 for centering and 2 more because this dropdown menu messes everything up). Also its not accurate, values to shift the spinners were chosen by eye measurement. Still: looks somewhat decent.
